# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name        = "M_anything"
version     = "1.0.0"
license     = "MIT"
author      = ["John S. Urban"]
maintainer  = "urbanjost@comcast.com"
copyright   = "Copyright 2021, John S. Urban"
description = "module to cast or promote intrinsic types"
categories  = ["types"]
keywords    = ["fortran", "cast", "mold" ]
homepage    = "https://github.com/urbanjost/M_anything.git"

[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   module-naming = true

[install]
   library = true

[[test]]
   name="test_suite_M_anything"
   source-dir="test"
   main="test_suite_M_anything.f90"
   [test.dependencies]
   # can use various registries, including local mirrors
   #M_framework = { namespace = "GPF" }
   #
   M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
   #
   # For off-line work use the GLINKS directory with links to the packages
   # ln -f -s $HOME/github/GLINKS GLINKS
   #M_framework  = { path = "GLINKS/M_framework" }
